name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Environment Variables
        run: |
          echo "SERVER_HOSTNAME=${{ secrets.SERVER_HOSTNAME }}" >> $GITHUB_ENV
          echo "JOB_ID=${{ secrets.JOB_ID }}" >> $GITHUB_ENV
          echo "ACCESS_TOKEN=${{ secrets.ACCESS_TOKEN }}" >> $GITHUB_ENV
      - name: install packages
        run: make install
      - name: lint
        run: make lint
      - name: test
        run: make test
      - name: format
        run: make format
      - name: run databricks job
        run: make job
      - name: deploy
        run: make deploy
      - name: Debug Visualizations Folder
        run: |
          echo "Listing contents of mylib/visualizations:"
          ls -R mylib/visualizations || echo "No files found in mylib/visualizations/"
      - name: Commit and Push Visualizations
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "GitHub Actions"
          git add mylib/visualizations/
          git commit -m "Add generated visualizations"
          git push
